name: Build and upload Docker image

on:
  push:
    branches:
    - master

jobs:
  build_armhf_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: antoniobl/armpackaging
        dockerfile: armhf.Dockerfile
        tags: armhf

  build_arm64_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: antoniobl/armpackaging
        dockerfile: arm64.Dockerfile
        tags: arm64
